### ISSUE TITLE
settings are not persistent

### ISSUE THREAD

**Issue by h2dden** [seedvault-app/seedvault#83]
as shown in the video

**Comment by h2dden** [comment]
https://mobile.twitter.com/h2dden/status/1243788431471202304

**Comment by stevesoltys** [comment]
I can reproduce this issue. It's strange, since it appears to happen indeterminately.

If you keep trying, it seems the settings will eventually be persisted.

**Comment by grote** [comment]
I had a look at the code and my first suspicion is that SettingsManager#blacklistedApps is changed on  `@UiThread`, but read from `@WorkerThread`. This isn't thread-safe and could cause the issue and would explain why it isn't deterministic.

**Comment by h2dden** [comment]
may I suggest, when it comes to backing up apps and apps' data, you change your philosophy from default opt-in to default opt-out?
I highlighted this bug to graphene os guys and I understood that even google-made apps, chrome/vanadium, do not properly handle the back up mechanism. So, in this context, attepting to backup everything and failing on several apps, doea not make sense to have a default opt-in.

**Comment by grote** [comment]
The default is supposed to be opt-out of backup for individual apps, might not be like that in practice due to the bug you've found.

**Comment by grote** [comment]
@h2dden do you have means to run your own builds of Seedvault to test a fix?

**Comment by h2dden** [comment]
not really

**Comment by grote** [comment]
@h2dden if you use GrapheneOS on Android 11, can you check if this is now fixed?

**Comment by h2dden** [comment]
I am running build RP1A.201005.004.2020.10.23.04
which is the latest.
The problem is not solved.
I will make a video in the morning: 23:50 now...

Oct 27, 2020 23:44:59 Torsten Grote <notifications@github.com>:

**Comment by h2dden** [comment]
I have made 2 videos. Let me know of any issues with viewing the videos
https://we.tl/t-btVkJedATq

**Comment by grote** [comment]
Thanks a lot for the videos. In addition to not persisting the settings, it also looks like there's a view recycling issue there. However, I am completely unable to reproduce any of this on my Android 11 or 10 device. Did you turn off all those apps or have they already been turned off from the beginning?

**Comment by h2dden** [comment]
From the begining some are on some are off.
The thing is I am not able to get all of them either all on or all off.
My intention is to have them all off as I am not using many apps and can easily manually install after a fresh OS flash/restore.

What is to do next, since you cannot replicate the issues?

**Comment by grote** [comment]
Maybe we find some other people that can replicate it? Post in the Graphene/Calyx/Copperhead channels and ask for people to try if it happens to them?

**Comment by grote** [comment]
haha, I think I found it. @h2dden have you tried to not tap exactly the switches, but tap anywhere else on the app line?

**Comment by h2dden** [comment]
indeed it seems to be working this way... which is strange

Nov 19, 2020 06:04:18 Torsten Grote <notifications@github.com>:
